### ISSUE TITLE
训练策略在RAW图像数据集上好像无效

### ISSUE THREAD

**Issue by Cynicarlos** [haoyuc/MaskedDenoise#29]
作者您好，我用您的baseline和masked策略分别在同一数据集上训练，训练同样的epoch，但masked策略收敛很慢，效果也不如baseline，且在其他RAW数据集上进行泛化性测试时，效果也大不如baseline，请问可能是什么原因呢？

**Comment by haoyuc** [comment]
个人感觉可能是这样一种情况：训练集的数据噪声的分布范围已经足够大，或者和测试集的噪声接近，所以无法发挥出我们的方法的效果（我们的方法在测试集和训练集存在较大分布差别的情况下能够有较好的性能）

**Comment by Cynicarlos** [comment]
感谢解答，还有一个问题，请问您的方法和baseline的实验设置如训练时长是一致的吗，我感觉使用mask之后收敛速度慢了很多，如果训练epoch或迭代次数一样，那么mask的performance应该不如baseline吧，这也是比较符合直觉的，毕竟输入的信息少很多

**Comment by haoyuc** [comment]
嗯嗯是的，如果是在和训练集一致的数据上进行测试的话，mask 的性能是肯定不如 baseline 的，毕竟 attention mask 损失了很多信息。所以我们的实验设置都是在和训练集不一致的数据上进行测试，这也是这个工作的目标。
